version: "3.6"
name: csrf-attack
services:
  rds:
    image: postgres
    container_name: csrf-attack
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "csrf-attack"
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on